name: Tests
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: WillAbides/setup-go-faster@v1.7.0
      id: setup-go-faster
      with:
        go-version: "*"

    - name: Install xorg-dev libgles-dev
      run: sudo apt update && sudo apt install xorg-dev libgles-dev

    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
